# Generated by Django 4.2.6 on 2023-10-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
